name: Android APK Build

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept Licenses
        run: yes | sdkmanager --licenses

      - name: Install SDK
        run: |
          sdkmanager \
          "platform-tools" \
          "platforms;android-34" \
          "build-tools;34.0.0"

      - name: Clear Gradle Cache
        run: |
          rm -rf ~/.gradle/caches
          rm -rf ~/.gradle/daemon

      - name: Permission
        run: chmod +x gradlew

      - name: Clean
        run: ./gradlew clean --stacktrace

      - name: Build APK
        run: ./gradlew assembleDebug --stacktrace --info

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk
